// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// LinearKernel__new
SEXP LinearKernel__new();
RcppExport SEXP _psvm4r_LinearKernel__new() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(LinearKernel__new());
    return rcpp_result_gen;
END_RCPP
}
// PolynomialKernel__new
SEXP PolynomialKernel__new(double degree, double constant);
RcppExport SEXP _psvm4r_PolynomialKernel__new(SEXP degreeSEXP, SEXP constantSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type constant(constantSEXP);
    rcpp_result_gen = Rcpp::wrap(PolynomialKernel__new(degree, constant));
    return rcpp_result_gen;
END_RCPP
}
// RbfKernel__new
SEXP RbfKernel__new(double gamma);
RcppExport SEXP _psvm4r_RbfKernel__new(SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(RbfKernel__new(gamma));
    return rcpp_result_gen;
END_RCPP
}
// LinearKernel__get
double LinearKernel__get(SEXP xp, const NumericVector& a, const NumericVector& b);
RcppExport SEXP _psvm4r_LinearKernel__get(SEXP xpSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(LinearKernel__get(xp, a, b));
    return rcpp_result_gen;
END_RCPP
}
// OneAgainstAllCSVC__new
SEXP OneAgainstAllCSVC__new(int num_classes, int num_dimensions, SEXP xp);
RcppExport SEXP _psvm4r_OneAgainstAllCSVC__new(SEXP num_classesSEXP, SEXP num_dimensionsSEXP, SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_classes(num_classesSEXP);
    Rcpp::traits::input_parameter< int >::type num_dimensions(num_dimensionsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(OneAgainstAllCSVC__new(num_classes, num_dimensions, xp));
    return rcpp_result_gen;
END_RCPP
}
// OneAgainstOneCSVC__new
SEXP OneAgainstOneCSVC__new(int num_classes, int num_dimensions, SEXP xp);
RcppExport SEXP _psvm4r_OneAgainstOneCSVC__new(SEXP num_classesSEXP, SEXP num_dimensionsSEXP, SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_classes(num_classesSEXP);
    Rcpp::traits::input_parameter< int >::type num_dimensions(num_dimensionsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(OneAgainstOneCSVC__new(num_classes, num_dimensions, xp));
    return rcpp_result_gen;
END_RCPP
}
// CSVC__train
void CSVC__train(SEXP xp, const NumericVector& training_attributes, const IntegerVector& training_labels, double C);
RcppExport SEXP _psvm4r_CSVC__train(SEXP xpSEXP, SEXP training_attributesSEXP, SEXP training_labelsSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type training_attributes(training_attributesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type training_labels(training_labelsSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    CSVC__train(xp, training_attributes, training_labels, C);
    return R_NilValue;
END_RCPP
}
// CSVC__predict
IntegerVector CSVC__predict(SEXP xp, const NumericVector& attributes);
RcppExport SEXP _psvm4r_CSVC__predict(SEXP xpSEXP, SEXP attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type attributes(attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(CSVC__predict(xp, attributes));
    return rcpp_result_gen;
END_RCPP
}
// SVC__num_sv
IntegerVector SVC__num_sv(SEXP xp);
RcppExport SEXP _psvm4r_SVC__num_sv(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(SVC__num_sv(xp));
    return rcpp_result_gen;
END_RCPP
}
// SVC__num_classes
int SVC__num_classes(SEXP xp);
RcppExport SEXP _psvm4r_SVC__num_classes(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(SVC__num_classes(xp));
    return rcpp_result_gen;
END_RCPP
}
// SVC__num_dimensions
int SVC__num_dimensions(SEXP xp);
RcppExport SEXP _psvm4r_SVC__num_dimensions(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    rcpp_result_gen = Rcpp::wrap(SVC__num_dimensions(xp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_psvm4r_LinearKernel__new", (DL_FUNC) &_psvm4r_LinearKernel__new, 0},
    {"_psvm4r_PolynomialKernel__new", (DL_FUNC) &_psvm4r_PolynomialKernel__new, 2},
    {"_psvm4r_RbfKernel__new", (DL_FUNC) &_psvm4r_RbfKernel__new, 1},
    {"_psvm4r_LinearKernel__get", (DL_FUNC) &_psvm4r_LinearKernel__get, 3},
    {"_psvm4r_OneAgainstAllCSVC__new", (DL_FUNC) &_psvm4r_OneAgainstAllCSVC__new, 3},
    {"_psvm4r_OneAgainstOneCSVC__new", (DL_FUNC) &_psvm4r_OneAgainstOneCSVC__new, 3},
    {"_psvm4r_CSVC__train", (DL_FUNC) &_psvm4r_CSVC__train, 4},
    {"_psvm4r_CSVC__predict", (DL_FUNC) &_psvm4r_CSVC__predict, 2},
    {"_psvm4r_SVC__num_sv", (DL_FUNC) &_psvm4r_SVC__num_sv, 1},
    {"_psvm4r_SVC__num_classes", (DL_FUNC) &_psvm4r_SVC__num_classes, 1},
    {"_psvm4r_SVC__num_dimensions", (DL_FUNC) &_psvm4r_SVC__num_dimensions, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_psvm4r(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
