# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.LinearKernel__new <- function() {
    .Call(`_psvm4r_LinearKernel__new`)
}

.LinearKernel__get <- function(xp, a, b) {
    .Call(`_psvm4r_LinearKernel__get`, xp, a, b)
}

.PolynomialKernel__new <- function(degree, constant) {
    .Call(`_psvm4r_PolynomialKernel__new`, degree, constant)
}

.PolynomialKernel__get <- function(xp, a, b) {
    .Call(`_psvm4r_PolynomialKernel__get`, xp, a, b)
}

.RbfKernel__new <- function(gamma) {
    .Call(`_psvm4r_RbfKernel__new`, gamma)
}

.RbfKernel__get <- function(xp, a, b) {
    .Call(`_psvm4r_RbfKernel__get`, xp, a, b)
}

.OAALinearKernel__new <- function(num_classes, num_dimensions, xp) {
    .Call(`_psvm4r_OAALinearKernel__new`, num_classes, num_dimensions, xp)
}

.OAALinearKernel__train <- function(xp, training_attributes, training_labels, C) {
    invisible(.Call(`_psvm4r_OAALinearKernel__train`, xp, training_attributes, training_labels, C))
}

.OAALinearKernel__predict <- function(xp, attributes) {
    .Call(`_psvm4r_OAALinearKernel__predict`, xp, attributes)
}

.OAALinearKernel__num_sv <- function(xp) {
    .Call(`_psvm4r_OAALinearKernel__num_sv`, xp)
}

.OAALinearKernel__num_classes <- function(xp) {
    .Call(`_psvm4r_OAALinearKernel__num_classes`, xp)
}

.OAALinearKernel__num_dimensions <- function(xp) {
    .Call(`_psvm4r_OAALinearKernel__num_dimensions`, xp)
}

.OAAPolynomialKernel__new <- function(num_classes, num_dimensions, xp) {
    .Call(`_psvm4r_OAAPolynomialKernel__new`, num_classes, num_dimensions, xp)
}

.OAAPolynomialKernel__get <- function(xp, training_attributes, training_labels, C) {
    invisible(.Call(`_psvm4r_OAAPolynomialKernel__train`, xp, training_attributes, training_labels, C))
}

.OAAPolynomialKernel__predict <- function(xp, attributes) {
    .Call(`_psvm4r_OAAPolynomialKernel__predict`, xp, attributes)
}

.OAAPolynomialKernel__num_sv <- function(xp) {
    .Call(`_psvm4r_OAAPolynomialKernel__num_sv`, xp)
}

.OAAPolynomialKernel__num_classes <- function(xp) {
    .Call(`_psvm4r_OAAPolynomialKernel__num_classes`, xp)
}

.OAAPolynomialKernel__num_dimensions <- function(xp) {
    .Call(`_psvm4r_OAAPolynomialKernel__num_dimensions`, xp)
}

.OAARbfKernel__new <- function(num_classes, num_dimensions, xp) {
    .Call(`_psvm4r_OAARbfKernel__new`, num_classes, num_dimensions, xp)
}

.OAARbfKernel__train <- function(xp, training_attributes, training_labels, C) {
    invisible(.Call(`_psvm4r_OAARbfKernel__train`, xp, training_attributes, training_labels, C))
}

.OAARbfKernel__predict <- function(xp, attributes) {
    .Call(`_psvm4r_OAARbfKernel__predict`, xp, attributes)
}

.OAARbfKernel__num_sv <- function(xp) {
    .Call(`_psvm4r_OAARbfKernel__num_sv`, xp)
}

.OAARbfKernel__num_classes <- function(xp) {
    .Call(`_psvm4r_OAARbfKernel__num_classes`, xp)
}

.OAARbfKernel__num_dimensions <- function(xp) {
    .Call(`_psvm4r_OAARbfKernel__num_dimensions`, xp)
}

.OAOLinearKernel__new <- function(num_classes, num_dimensions, xp) {
    .Call(`_psvm4r_OAOLinearKernel__new`, num_classes, num_dimensions, xp)
}

.OAOLinearKernel__train <- function(xp, training_attributes, training_labels, C) {
    invisible(.Call(`_psvm4r_OAOLinearKernel__train`, xp, training_attributes, training_labels, C))
}

.OAOLinearKernel__predict <- function(xp, attributes) {
    .Call(`_psvm4r_OAOLinearKernel__predict`, xp, attributes)
}

.OAOLinearKernel__num_sv <- function(xp) {
    .Call(`_psvm4r_OAOLinearKernel__num_sv`, xp)
}

.OAOLinearKernel__num_classes <- function(xp) {
    .Call(`_psvm4r_OAOLinearKernel__num_classes`, xp)
}

.OAOLinearKernel__num_dimensions <- function(xp) {
    .Call(`_psvm4r_OAOLinearKernel__num_dimensions`, xp)
}

.OAOPolynomialKernel__new <- function(num_classes, num_dimensions, xp) {
    .Call(`_psvm4r_OAOPolynomialKernel__new`, num_classes, num_dimensions, xp)
}

.OAOPolynomialKernel__train <- function(xp, training_attributes, training_labels, C) {
    invisible(.Call(`_psvm4r_OAOPolynomialKernel__train`, xp, training_attributes, training_labels, C))
}

.OAOPolynomialKernel__predict <- function(xp, attributes) {
    .Call(`_psvm4r_OAOPolynomialKernel__predict`, xp, attributes)
}

.OAOPolynomialKernel__num_sv <- function(xp) {
    .Call(`_psvm4r_OAOPolynomialKernel__num_sv`, xp)
}

.OAOPolynomialKernel__num_classes <- function(xp) {
    .Call(`_psvm4r_OAOPolynomialKernel__num_classes`, xp)
}

.OAOPolynomialKernel__num_dimensions <- function(xp) {
    .Call(`_psvm4r_OAOPolynomialKernel__num_dimensions`, xp)
}

.OAORbfKernel__new <- function(num_classes, num_dimensions, xp) {
    .Call(`_psvm4r_OAORbfKernel__new`, num_classes, num_dimensions, xp)
}

.OAORbfKernel__train <- function(xp, training_attributes, training_labels, C) {
    invisible(.Call(`_psvm4r_OAORbfKernel__train`, xp, training_attributes, training_labels, C))
}

.OAORbfKernel__predict <- function(xp, attributes) {
    .Call(`_psvm4r_OAORbfKernel__predict`, xp, attributes)
}

.OAORbfKernel__num_sv <- function(xp) {
    .Call(`_psvm4r_OAORbfKernel__num_sv`, xp)
}

.OAORbfKernel__num_classes <- function(xp) {
    .Call(`_psvm4r_OAORbfKernel__num_classes`, xp)
}

.OAORbfKernel__num_dimensions <- function(xp) {
    .Call(`_psvm4r_OAORbfKernel__num_dimensions`, xp)
}

