# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.LinearKernel__new <- function() {
    .Call(`_psvm4r_LinearKernel__new`)
}

.PolynomialKernel__new <- function(degree, constant) {
    .Call(`_psvm4r_PolynomialKernel__new`, degree, constant)
}

.RbfKernel__new <- function(gamma) {
    .Call(`_psvm4r_RbfKernel__new`, gamma)
}

.Kernel__get <- function(xp, a, b) {
    .Call(`_psvm4r_LinearKernel__get`, xp, a, b)
}

.OneAgainstAllCSVC__new <- function(num_classes, num_dimensions, xp) {
    .Call(`_psvm4r_OneAgainstAllCSVC__new`, num_classes, num_dimensions, xp)
}

.OneAgainstOneCSVC__new <- function(num_classes, num_dimensions, xp) {
    .Call(`_psvm4r_OneAgainstOneCSVC__new`, num_classes, num_dimensions, xp)
}

.CSVC__train <- function(xp, training_attributes, training_labels, C) {
    invisible(.Call(`_psvm4r_CSVC__train`, xp, training_attributes, training_labels, C))
}

.CSVC__predict <- function(xp, attributes) {
    .Call(`_psvm4r_CSVC__predict`, xp, attributes)
}

.CSVC__num_sv <- function(xp) {
    .Call(`_psvm4r_SVC__num_sv`, xp)
}

.CSVC__num_classes <- function(xp) {
    .Call(`_psvm4r_SVC__num_classes`, xp)
}

.CSVC__num_dimensions <- function(xp) {
    .Call(`_psvm4r_SVC__num_dimensions`, xp)
}

